
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: monitoring-node
  template:
    metadata:
      labels:
        app: monitoring-node
    spec:
      containers:
      - name: monitoring-node-container
        image: monitoring_node_image
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_IP
          value: "central-server-service"
---
apiVersion: v1
kind: Service
metadata:
  name: central-server-service
spec:
  selector:
    app: central-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
